### ISSUE TITLE
想请教关于爬虫的问题

### ISSUE THREAD

**Issue by yourcolour** [billjyc/pocket48#11]
首先很感谢开源这个项目 让大家都能容易写出适合自己的机器人
另外 想请教一下 自从口袋48升级到5.1之后 (我猜是用了SSL pinning) 用charles已经抓不到数据了.
然后我用安卓5.0的机子装了xposed 和just trust me 模块 依然无法绕过验证
请问您是怎么成功抓到数据的? (因为我看到您代码的口袋版本已经是5.2的了)

**Comment by billjyc** [comment]
额，怎么说呢，其实我也是很久没抓到包了，但是github上还是有其他的类似项目会有新的接口更新的，相信他们应该会有自己的方法抓到数据的
举例： https://github.com/anguiao/48Tools
https://github.com/allofee/pocket48_rooms

**Comment by yourcolour** [comment]
@billjyc 感谢!!!
