### ISSUE TITLE
想问下大哥请求头PA值的盐码在哪获取到的

### ISSUE THREAD

**Issue by p845591892** [billjyc/pocket48#13]
今晚又更新了，PA值对不上，接口又用不了了，求大哥指点

**Comment by billjyc** [comment]
813613889
加这个QQ群，找一个叫”Lgyzero“的大佬，他搞了个接口，可以获取PA值，（把信息提供给他，他会给你一个token来调用接口）

> 今晚又更新了，PA值对不上，接口又用不了了，求大哥指点
