### ISSUE TITLE
请问 pa 是怎么算出来的？

### ISSUE THREAD

**Issue by wdwind** [billjyc/pocket48#16]
请问 pa 是怎么算出来的？能否分享一下方法？

谢谢

**Comment by billjyc** [comment]
813613889
加这个QQ群，找一个叫”Lgyzero“的大佬，他搞了个接口，可以获取PA值，（把信息提供给他，他会给你一个token来调用接口）

**Comment by billjyc** [comment]
> 请问 pa 是怎么算出来的？能否分享一下方法？
> 
> 谢谢
813613889
加这个QQ群，找一个叫”Lgyzero“的大佬，他搞了个接口，可以获取PA值，（把信息提供给他，他会给你一个token来调用接口）

**Comment by yie1d** [comment]
老哥，这个群是没了吗？
